import { GoogleGenAI } from "@google/genai";
import fetch from 'node-fetch';

const CONFIG = {
    GEMINI_KEY: process.env.GEMINI_API_KEY,
    // Thread ID is attached to ensure it lands in the Daily Doodle channel
    DISCORD_URL: "https://discord.com/api/webhooks/1475400524881854495/A2eo18Vsm-cIA0p9wN-XdB60vMdEcZ5PJ1MOGLD5sRDM1weRLRk_1xWKo5C7ANTzjlH2?thread_id=1475685722341245239"
};

async function main() {
    try {
        const client = new GoogleGenAI({ apiKey: CONFIG.GEMINI_KEY });
        const dateStr = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric' });

        console.log(`--- Starting Daily Doodle for ${dateStr} ---`);

        // 1. Get Holiday Data (Defaulting to 2.5 Flash)
        const textResult = await client.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [{ role: "user", parts: [{ text: `Today is ${dateStr}. Identify a fun national holiday. Return ONLY JSON: {"holiday": "Name", "fact": "One sentence fun fact"}` }] }]
        });
        
        const data = JSON.parse(textResult.text.replace(/```json|```/g, ""));
        console.log(`Holiday found: ${data.holiday}`);

        // Small 5s pause to avoid the "Free Tier" burst limit
        await new Promise(r => setTimeout(r, 5000));

        // 2. Generate Image (Defaulting to 2.5 Flash)
        const imgPrompt = `A vibrant digital illustration for "${data.holiday}". 
        The text "${data.holiday}" must be clearly rendered in a bold white font at the top. 
        Characters: A small, round, yellow bear with a cream belly and a cheerful pink pill-shaped jellybean wearing a teal baseball cap. 
        Style: Gaming aesthetic. NO other text.`;

        const imageResult = await client.models.generateContent({
            model: "gemini-2.5-flash",
            contents: [{ role: "user", parts: [{ text: imgPrompt }] }]
        });

        // 3. Robust Image URL extraction
        const imagePart = imageResult.candidates?.[0]?.content?.parts?.find(p => p.inlineData || p.fileData);
        let imageUrl = imagePart?.inlineData 
            ? `data:${imagePart.inlineData.mimeType};base64,${imagePart.inlineData.data}` 
            : "https://via.placeholder.com/512.png?text=Art+Rendering...";

        // 4. Post to Discord
        const res = await fetch(CONFIG.DISCORD_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                embeds: [{
                    title: `🎨 Daily Doodle: ${data.holiday}`,
                    description: `**Did you know?** ${data.fact}`,
                    image: { url: imageUrl },
                    color: 0x00FFFF,
                    footer: { text: "Generated by Gemini 2.5 Flash" }
                }]
            })
        });

        if (res.ok) {
            console.log("Success! Posted to Discord.");
        } else {
            const errorBody = await res.text();
            console.error(`Discord rejected the post: ${res.status} - ${errorBody}`);
        }

    } catch (err) {
        console.error("Critical Bot Error:", err.message);
        // If it's a quota error, we give a friendly heads-up
        if (err.message.includes("429")) {
            console.log("QUOTA TIP: If this is a new API key, wait 60 seconds before trying again.");
        }
        process.exit(1);
    }
}

main();
